FROM ghcr.io/acts-project/ubuntu2004:v41
RUN \
    apt-get update        && \
    apt-get install --yes    \
        build-essential      \
        gfortran             \
        python3.8-dev        \
        python3-pip          \
	    python3.8-venv	     \
        git-lfs              \
        vim                  \
        wget              && \
    apt-get clean all